/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javalesson2;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class MstFrame extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    ArrayList<Phong> phongList = new ArrayList<>();
    /** Creates new form MstFrame */
    public MstFrame() {
        initComponents();
        tableModel = (DefaultTableModel) tblPhong.getModel();
        showPhong();
    }
    private void showPhong() {
        
        PhongModify md = new javalesson2.PhongModify();
//        ArrayList<Phong> phongList = new ArrayList<>();
        try {
            phongList = md.findAll();
        } catch (SQLException ex) {
            Logger.getLogger(PhongModify.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tableModel.setRowCount(0);
        String str []= {"Nhà trọ giá rẻ","Ký túc xá giá rẻ","Hotel","Homestay"};

        
        phongList.forEach((phong) -> {
            tableModel.addRow(new Object[] {phong.getID(), phong.getTensanpham(),
                                phong.getGiasanpham(),phong.getHinhanhsanpham(),
                                phong.getMotasanpham(),str[Integer.parseInt(phong.getIDsanpham())-1]});
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbLoaisp = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTenphong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGiaphong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHinhanh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMota = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnFindid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhong = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Manager MST"));

        jLabel1.setText("ID :");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Loại Phòng: ");

        cbLoaisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhà trọ giá rẻ", "Ký túc xá giá rẻ", "Hotel", "Homestay" }));

        jLabel3.setText("Tên Phòng :");

        txtTenphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenphongActionPerformed(evt);
            }
        });

        jLabel4.setText("Giá Phòng :");

        txtGiaphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaphongActionPerformed(evt);
            }
        });

        jLabel5.setText("Hình ảnh (link) :");

        txtHinhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHinhanhActionPerformed(evt);
            }
        });

        jLabel6.setText("Mô tả :");

        txtMota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotaActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find By Name");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnFindid.setText("Find By ID");
        btnFindid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindidActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel6)
                            .add(jLabel2)
                            .add(jLabel5)
                            .add(jLabel3)
                            .add(jLabel1))
                        .add(41, 41, 41)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cbLoaisp, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txtMota)
                            .add(txtID)
                            .add(txtTenphong)
                            .add(txtGiaphong)
                            .add(txtHinhanh)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(btnSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(72, 72, 72)
                        .add(btnReset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 74, Short.MAX_VALUE)
                        .add(btnDelete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(9, 9, 9)))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(103, 103, 103)
                .add(btnFind, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(btnFindid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtTenphong, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .add(jLabel3))
                .add(13, 13, 13)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtGiaphong, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtHinhanh, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtMota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(jLabel6)))
                .add(40, 40, 40)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cbLoaisp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(85, 85, 85)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnReset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnDelete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnFind, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .add(btnFindid, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(17, 17, 17))
        );

        tblPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Phòng", "Giá Phòng", "Hình ảnh (link)", "Mô tả", "Loại Sản phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPhong);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1)))
                .add(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtTenphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenphongActionPerformed

    private void txtGiaphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaphongActionPerformed

    private void txtHinhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHinhanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHinhanhActionPerformed

    private void txtMotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotaActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên tìm kiếm: ");
        if(input != null && input.length()>0){
            phongList = PhongModify.findbyname(input);
            tableModel.setRowCount(0);
            String str []= {"Nhà trọ giá rẻ","Ký túc xá giá rẻ","Hotel","Homestay"};
            phongList.forEach((phong) -> {
                tableModel.addRow(new Object[] {phong.getID(), phong.getTensanpham(),
                                    phong.getGiasanpham(),phong.getHinhanhsanpham(),
                                    phong.getMotasanpham(),str[Integer.parseInt(phong.getIDsanpham())-1]});
            });
        }else{
            showPhong();
        }
                
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblPhong.getSelectedRow();
        if (selectedIndex >=0){

            Phong phong = phongList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa phòng?", "Comfirm", JOptionPane.YES_NO_OPTION);
            System.out.println("Option: " +option);
            
            if (option == 0){
                PhongModify md = new javalesson2.PhongModify();
                md.delete(phong.getID());
                showPhong();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtGiaphong.setText("");
        txtMota.setText("");
        txtTenphong.setText("");
        txtHinhanh.setText("");
        cbLoaisp.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int ID = Integer.parseInt(txtID.getText());
        String Tenphong = txtTenphong.getText();
        String Giaphong = txtGiaphong.getText();
        String Mota = txtMota.getText();
        String Hinhanh = txtHinhanh.getText();
        String Loaisp = cbLoaisp.getSelectedItem().toString();
        String IDsanpham; 
        if (Loaisp == "Nhà trọ giá rẻ"){
            IDsanpham="1";
        }
        else if (Loaisp == "Ký túc xá giá rẻ"){
            IDsanpham="2";
        }else if (Loaisp == "Hotel"){
            IDsanpham="3";
        }else{
            IDsanpham="4";
        }
        Phong p = new Phong(ID,Tenphong,Giaphong,Hinhanh,Mota,IDsanpham);
        
        PhongModify md = new javalesson2.PhongModify();
        md.insert(p);
        showPhong();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFindidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindidActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập ID Phòng cần tìm kiếm: ");
        if(input != null && input.length()>0){
            phongList = PhongModify.findbyid(input);
            tableModel.setRowCount(0);
            String str []= {"Nhà trọ giá rẻ","Ký túc xá giá rẻ","Hotel","Homestay"};
            phongList.forEach((phong) -> {
                tableModel.addRow(new Object[] {phong.getID(), phong.getTensanpham(),
                                    phong.getGiasanpham(),phong.getHinhanhsanpham(),
                                    phong.getMotasanpham(),str[Integer.parseInt(phong.getIDsanpham())-1]});
            });
        }else{
            showPhong();
        }
    }//GEN-LAST:event_btnFindidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFindid;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbLoaisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhong;
    private javax.swing.JTextField txtGiaphong;
    private javax.swing.JTextField txtHinhanh;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtTenphong;
    // End of variables declaration//GEN-END:variables

}
